stages:
 - log
 - stop
 - deploy
# 项目主目录 
variables:
  # 项目的目录 (全局变量)
  GITLAB_CI_PATH: ""
  # 项目的日志目录 (全局变量)
  LOG_PATH: ""
  
log_job:
 stage: log
 only:
  - web  # 只可以通过gitlab网页端提交, 不可提交代码的时候便提交
 script:
  -  GITLAB_CI_PATH=`pwd`
  -  cd ..
  -  mkdir logs
 tags:
  - yf_mall_prod  # 配置的为设置-ci/cd -runner 中的tags便签
 allow_failure: true # 允许上述代码失败
 
stop_job:
 stage: stop
 only:
  - web # 只可以通过gitlab网页端提交, 不可提交代码的时候便提交
 script:
  -  echo "删除pm2 yf_mall_8205 的进程"
  -  pm2 delete yf_mall_8205
 tags:
  - changcheng_prod  # 配置的为设置-ci/cd -runner 中的tags便签
 allow_failure: true  # 允许上述代码失败

deploy_job:
 stage: deploy
 only:
  - web
 script:
  -  GITLAB_CI_PATH=`pwd`
  -  cd ../logs
  -  LOG_PATH=`pwd`
  
  -  echo "执行cnpm install操作"
  -  cd $GITLAB_CI_PATH &&  cnpm install
  -  echo "添加软链接"
  -  ln -s ./node_modules/nuxt/bin/nuxt ./nuxt

  -  echo "------------ 休息3秒--------------"
  -  sleep 3

  -  echo "--------开始执行nuxt build命令-------"
  -  cd $GITLAB_CI_PATH && ./nuxt build

  -  echo "执行pm2线程守护"
  -  pm2 start npm --name "yf_mall_8205" -e $LOG_PATH/nuxterr.log -o $LOG_PATH/nuxtout.log -i 2 -- run start

 tags:
  - changcheng_prod